server {
    listen 80;
    listen [::]:80;
    server_name yt-oauth.mironbot.ru;

    root /home/appuser/dev/kostya/avatar_kostya/www/yt-oauth;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    location ~* \.(html|css|js|ico|txt)$ {
        add_header Cache-Control "public, max-age=300";
    }
}
