-- Расширение users под UserStorage / access / followup / агент Biblia.
-- Идемпотентно: ADD COLUMN IF NOT EXISTS.

BEGIN;

ALTER TABLE users ADD COLUMN IF NOT EXISTS is_banned BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS onboarding_complete BOOLEAN DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS questions_asked INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS bd DATE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS profile TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS timezone_offset INTEGER;
ALTER TABLE users ADD COLUMN IF NOT EXISTS agent_session_id TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS followup_step INTEGER;
ALTER TABLE users ADD COLUMN IF NOT EXISTS followup_started_at TIMESTAMPTZ;
ALTER TABLE users ADD COLUMN IF NOT EXISTS followup_last_action TIMESTAMPTZ;
ALTER TABLE users ADD COLUMN IF NOT EXISTS feedback_text TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS feedback_given_at TIMESTAMPTZ;
ALTER TABLE users ADD COLUMN IF NOT EXISTS first_answer_rating TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS rated_at TIMESTAMPTZ;
ALTER TABLE users ADD COLUMN IF NOT EXISTS referral_bonus_granted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;
ALTER TABLE users ADD COLUMN IF NOT EXISTS mailing_consent BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_mailing_at TIMESTAMPTZ;
ALTER TABLE users ADD COLUMN IF NOT EXISTS mailing_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS donation_button_click INTEGER NOT NULL DEFAULT 0;

COMMIT;
